In [1]:
import pandas as pd

In [2]:
doi_df_journal = pd.DataFrame({
    "DOI": [
        "10.1371/journal.pcbi.1004668",
        "10.21105/joss.01035",
        "10.12688/f1000research.18866.2",
        "10.1038/s41598-019-52881-4",
        "10.1186/s12859-019-3171-0"],
    "journal": [
        "PLoS Comput Biol",
        "JOSS",
        "F1000Res",
        "Sci Rep",
        "BMC Bioinformatics"]})

doi_df_first_author = pd.DataFrame({
    "DOI": [
        "10.1371/journal.pcbi.1004668",
        "10.21105/joss.01035",
        "10.21105/joss.01006",
        "10.12688/f1000research.18866.2",
        "10.1186/s12859-019-3171-0"],
    "first_author": [
        "Blischak",
        "Sparks",
        "Granger",
        "Thang",
        "Chen"]})

In [3]:
doi_df_journal

                              DOI             journal
0    10.1371/journal.pcbi.1004668    PLoS Comput Biol
1             10.21105/joss.01035                JOSS
2  10.12688/f1000research.18866.2            F1000Res
3      10.1038/s41598-019-52881-4             Sci Rep
4       10.1186/s12859-019-3171-0  BMC Bioinformatics

In [4]:
doi_df_first_author

                              DOI first_author
0    10.1371/journal.pcbi.1004668     Blischak
1             10.21105/joss.01035       Sparks
2             10.21105/joss.01006      Granger
3  10.12688/f1000research.18866.2        Thang
4       10.1186/s12859-019-3171-0         Chen

In [6]:
# inner join (default)
doi_df_first_author.merge(doi_df_journal, on="DOI")

                              DOI first_author             journal
0    10.1371/journal.pcbi.1004668     Blischak    PLoS Comput Biol
1             10.21105/joss.01035       Sparks                JOSS
2  10.12688/f1000research.18866.2        Thang            F1000Res
3       10.1186/s12859-019-3171-0         Chen  BMC Bioinformatics

In [7]:
doi_df_first_author.merge(doi_df_journal, on="DOI", how="left")

                              DOI first_author             journal
0    10.1371/journal.pcbi.1004668     Blischak    PLoS Comput Biol
1             10.21105/joss.01035       Sparks                JOSS
2             10.21105/joss.01006      Granger                 NaN
3  10.12688/f1000research.18866.2        Thang            F1000Res
4       10.1186/s12859-019-3171-0         Chen  BMC Bioinformatics

In [8]:
doi_df_first_author.merge(doi_df_journal, on="DOI", how="right")

                              DOI first_author             journal
0    10.1371/journal.pcbi.1004668     Blischak    PLoS Comput Biol
1             10.21105/joss.01035       Sparks                JOSS
2  10.12688/f1000research.18866.2        Thang            F1000Res
3      10.1038/s41598-019-52881-4          NaN             Sci Rep
4       10.1186/s12859-019-3171-0         Chen  BMC Bioinformatics

In [9]:
doi_df_first_author.merge(doi_df_journal, on="DOI", how="outer")

                              DOI first_author             journal
0    10.1371/journal.pcbi.1004668     Blischak    PLoS Comput Biol
1             10.21105/joss.01035       Sparks                JOSS
2             10.21105/joss.01006      Granger                 NaN
3  10.12688/f1000research.18866.2        Thang            F1000Res
4       10.1186/s12859-019-3171-0         Chen  BMC Bioinformatics
5      10.1038/s41598-019-52881-4          NaN             Sci Rep

In [12]:
doi_df_first_author_2 = pd.DataFrame({
    "doi": [
        "10.1371/journal.pcbi.1004668",
        "10.21105/joss.01035",
        "10.21105/joss.01006",
        "10.12688/f1000research.18866.2",
        "10.1186/s12859-019-3171-0"],
    "first_author": [
        "Blischak",
        "Sparks",
        "Granger",
        "Thang",
        "Chen"]})

In [17]:
doi_df_first_author_2.merge (doi_df_journal, left_on="doi", right_on="DOI", how="outer")

,doi,first_author,DOI,journal
0,10.1371/journal.pcbi.1004668,Blischak,10.1371/journal.pcbi.1004668,PLoS Comput Biol
1,10.21105/joss.01035,Sparks,10.21105/joss.01035,JOSS
2,10.21105/joss.01006,Granger,NaN,NaN
3,10.12688/f1000research.18866.2,Thang,10.12688/f1000research.18866.2,F1000Res
4,10.1186/s12859-019-3171-0,Chen,10.1186/s12859-019-3171-0,BMC Bioinformatics
5,NaN,NaN,10.1038/s41598-019-52881-4,Sci Rep

In [18]:
merged_df = doi_df_first_author_2.merge (doi_df_journal, left_on="doi", right_on="DOI", how="outer")

In [21]:
merged_df.to_csv("merged_df.csv", index=False, sep="\t")